### ISSUE TITLE
No updater in settings

### ISSUE THREAD

**Issue by DeadPool-4422** [PixelOS-Devices-old/device_xiaomi_sweet#2]
As the title says i cannot open the updater in the settings

although searching for updater does brings something up but when i click it , it only opens the system settings page and there's no updater option there

i'm adding the screenshots below for clarification
![Screenshot_20230407-200038_Settings Services](https://user-images.githubusercontent.com/123509971/230626431-b3b7c086-331e-4e8d-bf85-84e1cdb48666.png)
![Screenshot_20230407-200044_Settings](https://user-images.githubusercontent.com/123509971/230626471-3336c2be-4a7c-442e-9d4c-6b47e008eac8.png)

**Comment by basamaryan** [comment]
Not a device issue, how will there be an updater back then if there was no support for OTA in the first place?
