### ISSUE TITLE
Light mode recent  Google searches are looking dark 

### ISSUE THREAD

**Issue by LalithYagnavalkya** [PixelOS-Devices-old/device_xiaomi_sweet#3]
TQ2A.230505.002.A1 PixelOS_sweet-13.0-20230510-2026

### Version

thirteen

### Describe the Bug

I'm using redmi not 10 pro.

Here the recent searches color looks bad in light mode 
please fix this

![Screenshot_20230624-093936](https://github.com/PixelExperience/android-issues/assets/69410566/0ed26bab-a8d2-4780-bb1b-a31fb2a21e01)

### Steps to Reproduce

Just open search in home page and you will see the recent results are looking dark. Which can be better 

### Expected Behavior

The search results colours shouldn't be that dark

**Comment by basamaryan** [comment]
This is not an issue with the tree. Stop creating GitHub issues in every repository you see.

**Comment by LalithYagnavalkya** [comment]
Sorry for that, where can I give a feed back

**Comment by basamaryan** [comment]
@LalithYagnavalkya We don’t need you to, it is already known.
